# Generated by Django 4.2.7 on 2023-11-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='tags',
            field=models.CharField(blank=True, help_text='Enter tags separated by commas', max_length=255),
        ),
    ]
